apiVersion: v1
kind: Service
metadata:
  name: quick-chat-api
  namespace: quick-chat
spec:
  type: ClusterIP
  selector:
    app: quick-chat-api
  ports:
    - port: 5000
      targetPort: 5000
      name: http
