apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: quick-chat
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "quick-chat-api"
        metrics_path: /metrics
        static_configs:
          - targets: ["quick-chat-api:5000"]
