apiVersion: v1
kind: Secret
metadata:
  name: quick-chat-secrets
  namespace: quick-chat
type: Opaque
stringData:
  jwt-secret: "YOUR_JWT_SECRET"
  cloudinary-cloud-name: "your_cloud_name"
  cloudinary-api-key: "your_api_key"
  cloudinary-api-secret: "your_api_secret"
